# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcCode.bartender_pb2 as bartender__pb2


class BartenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeDrink = channel.unary_unary(
            '/Bartender/MakeDrink',
            request_serializer=bartender__pb2.DrinkRequest.SerializeToString,
            response_deserializer=bartender__pb2.DrinkResponse.FromString,
        )


class BartenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeDrink(self, request, context):
        """make a drink
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BartenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'MakeDrink': grpc.unary_unary_rpc_method_handler(
            servicer.MakeDrink,
            request_deserializer=bartender__pb2.DrinkRequest.FromString,
            response_serializer=bartender__pb2.DrinkResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Bartender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Bartender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeDrink(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bartender/MakeDrink',
                                             bartender__pb2.DrinkRequest.SerializeToString,
                                             bartender__pb2.DrinkResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
